### ISSUE TITLE
nRF serial logging

### ISSUE THREAD

**Issue by SamGeens** [MOSAIC-LoPoW/octa-stack-students#20]
If you need serial logging for the nRF examples don't forget the `NRF_LOG_FLUSH();`!

Also add the following includes:
```
#include "nrf_delay.h"

#include "nrf_log.h"
#include "nrf_log_ctrl.h"
#include "nrf_log_default_backends.h"
```

And SRC_FILES in make:
```
  $(SDK_ROOT)/components/libraries/log/src/nrf_log_backend_rtt.c \
  $(SDK_ROOT)/components/libraries/log/src/nrf_log_backend_serial.c \
  $(SDK_ROOT)/components/libraries/log/src/nrf_log_backend_uart.c \
  $(SDK_ROOT)/components/libraries/log/src/nrf_log_default_backends.c \
```

**Example code:**
```
int main(void)
{
    APP_ERROR_CHECK(NRF_LOG_INIT(NULL));
    NRF_LOG_DEFAULT_BACKENDS_INIT();
    NRF_LOG_INFO("Example started.");

    while (true)
    {
        // Print hello
        NRF_LOG_INFO("Hello");
        nrf_delay_ms(500);
        NRF_LOG_FLUSH();
    }
}
```

Issue can be closed immediately.

**Comment by Klievan** [comment]
If you are going to start using the nRF52 on the OCTA, chances are high that your UART logging over NRF_LOG will not be working since you'll be using the main UART for communication with the OCTA. 

An easy fix for this is to switch the NRF_LOG driver to RTT, which can send data over the JLINK programmers you will be getting next week. This can be done by setting NRF_LOG_BACKEND_RTT_ENABLED to 1 in your config, and by using an RTT client.

Segger Embedded Studio automatigically displays those logs in the console. 

VSCode users can either use the JLinkRTTClient commandline command during an active debug session, which should work out of the box if you have JLink in your path (you need an active debug session for this), or use the JLinkRTTViewer GUI application.
