### ISSUE TITLE
Segger Licence Problem

### ISSUE THREAD

**Issue by yalcinpak** [MOSAIC-LoPoW/octa-stack-students#41]
Finally I found correct configuration to flash my ble module on octa board. You have to connect jlink edu usb cable and stm32 usb cable. Otherwise j-flash can not see your ble module. I choosed nrf52832_XXAB as a target device. You need to choose SN 269401981 when you click connect. Then you add your hex code and start to production programming , you will receive licence problem. There is free licience option on segger web site for educational use. But there is no link to download educational licience. Segger just give information about that.  https://www.segger.com/purchase/licensing/license-sfl/
![segger licience problem](https://user-images.githubusercontent.com/50590035/145018831-73f3ffc7-dee4-4e65-9e22-7d043225da9e.JPG)
Has anyone idea about segger edu licence?

**Comment by MatsDeMeyer** [comment]
I have no idea about the license, but I do know that you can program it without any problems using the the nrf command line tools (nrfjprog in particular): https://www.nordicsemi.com/Products/Development-tools/nrf-command-line-tools/download

If you compile for the correct board, you can use `make flash_softdevice` and 'make flash` to flash the softdevice and application to the BLE chip in the octa.

You do need to power the octa board as you say, a simple trick to not have two JLinks connected is to power the octa board by using the FTDI usb connector on the octa instead of the ST-Link/JLink connector on the nucleo.
