### ISSUE TITLE
Target -> makefile error

### ISSUE THREAD

**Issue by yalcinpak** [MOSAIC-LoPoW/octa-stack-students#7]
Hello my colleagues and teachers, I received an error about extension for debugging makefile. I have to add something to "#target" according to my research. But I couldn't. Anyone can help me
![Capture1](https://user-images.githubusercontent.com/50590035/137459783-400ab96b-b3bd-4f17-8ea5-aff9e5d07863.JPG)
?

**Comment by MatsDeMeyer** [comment]
It's not needed to debug the Makefile. The one that CubeMX generates should work.
Are you able to compile the code? By running "make" from the folder of your project (abc1)?

Alternatively, you could create an entry in the tasks.json file in the .vscode folder to compile, similar to the ones in the octa-stack.
For flashing/debugging, you can also create an entry in the launch.json file. Most of the parameters are the same, just make sure the paths point to you CubeMX project instead of the octa-stack applications.

**Comment by yalcinpak** [comment]
Yes, I am able to compile the code using "make". I added some entry in the launch.json file and problem is solved. I got the idea. Thanks for your help.  ( info:  I didn't add anything here "makefile-> #target")
